version: '2' 

services:
  postgres:
    build: ./postgresql
    ports:
      - "5432:5432"
    volumes:
      - data_postgres:/var/lib/postgresql/data
    networks:
      - magpie
  web:
    depends_on:
      - postgres
    build: ./web
    restart: always
    environment:
      - FLASK_APP=run.py
      - FLASK_ENV=development
      - FLASK_DEBUG=1
    ports:
      - "5000:5000"
    volumes:
      - data_files:/var/scratch/uploads
      - ./web:/var/scratch/web
    networks:
      - magpie

volumes:
  data_postgres:
  data_files:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /tmp/ingest

networks:
  magpie:
